railway/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('reservation.urls'))
]

reservation/urls.py
from django.urls import path,include

from . import views

urlpatterns = [
    path('',views.index,name="index"),
    path('loginform/',views.loginform,name="loginform"),
    path('login/',views.login,name="login"),
    path('registerform/',views.registerform,name="registerform"),
    path('register/',views.register,name="register"),
    path('logout/',views.logout,name="logout"),    
    path('trainform/',views.trainform,name="trainform"),    
    path('addtrain/',views.addtrain,name="addtrains"),   
    path('<train_id>',views.train_id,name="train_id"),
    path('book/',views.book,name="book"),   
    path('bookform/',views.bookform,name="bookform"),
    path('mybooking/',views.mybooking,name="mybooking"),
    path('booking/<train_id>',views.booking,name="booking"),
    
]

reservation/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class trains(models.Model):
    train_name=models.CharField(max_length=50)
    source=models.CharField(max_length=50)
    destination=models.CharField(max_length=50)
    date=models.DateField()
    time=models.TimeField(auto_now=False, auto_now_add=False)
    price=models.FloatField(default=120)
    seats_available=models.IntegerField()

class person(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name=models.CharField(max_length=50)
    age=models.IntegerField()
    gender=models.CharField(max_length=50,choices=(("MALE","MALE"),("FEMALE","FEMALE"),("OTHER","OTHER")))
    email=models.EmailField(max_length=254)
    date_and_time_of_booking=models.DateTimeField(auto_now_add=True)
    phone_number = models.IntegerField(max_length=10)
    train=models.ForeignKey(trains, on_delete=models.CASCADE)


reservation/forms.py
from django.forms import ModelForm
from .models import person
from django.contrib.auth.models import User

class PersonForm(ModelForm):
    class Meta:
        model = person
        fields = '__all__'
        exclude = ['user', 'date_and_time_of_booking', 'train','email']


reservation/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout

from .models import trains, person
from .forms import PersonForm

def index(request):
    lis = trains.objects.all()
    return render(request, './viewtrains.html', {"lis": lis})


def loginform(request):
    return render(request, './login.html')


def login(request):
    u = request.POST
    user = authenticate(request, username=u['name'], password=u['password'])
    if user is not None:
        auth_login(request, user)
        context = {
            'msg': "Login Successsful"
        }
    else:
        context = {
            'msg': "Error User is not registered/invalid"
        }
    return render(request, './error.html', context)


def registerform(request):
    return render(request, './register.html')


def register(request):
    user = request.POST
    u = User.objects.create_user(user['name'], user['email'], user['password'])
    u.save()
    context = {
        'msg': "Registeration Successsful"
    }
    return render(request, './error.html', context)


def logout(request):
    auth_logout(request)

    context = {
        'msg': "Logout Successful"
    }
    return render(request, './error.html', context)


def trainform(request):
    if request.user.is_superuser:
        return render(request, './addtrain.html')
    else:
        return render(request, './error.html', {'msg': "Not an Admin"})


def addtrain(request):
    l = trains(source=request.POST['source'], destination=request.POST['destination'], date=request.POST['date'],
               time=request.POST['time'], seats_available=request.POST['seats_available'],train_name=request.POST['train_name'],price=request.POST['price'])
    l.save()
    return render(request, './error.html', {'msg': "Successfully Added"})


def train_id(request, train_id):
    if not request.user.is_superuser:
        return render(request, './error.html', {'msg': "Not an Admin"})

    l = trains.objects.get(pk=train_id)
    persons = l.person_set.all()
    context = {
        'train': l,
        'persons': persons
    }
    return render(request, './viewperson.html', context)

temp={}
def book(request):
    global temp
    if request.user.is_authenticated:
        t = trains.objects.filter(
            source=request.POST['source'], 
            destination=request.POST['destination'], 
            date=request.POST['date'],
        )
        return render(request, './trainsavailable.html', {'trains': t})
    else:
        return render(request, './error.html', {'msg': "Not a valid user. Please Login to continue"})


def booking(request, train_id):
    if request.user.is_authenticated:
        form = PersonForm()
        if request.method == 'POST':

            tt = trains.objects.get(pk=train_id)
            if tt.seats_available == 0:
                return render(request, './error.html', {'msg': "Seats full"})
            tt.seats_available -= 1

            #p = person(train=tt, name=temp['name'], email=request.user.email,age=temp['age'],gender=temp['gender'])
            #p.save()
            a = person.objects.create(
                user = request.user,
                name = request.POST.get('name'),
                age = request.POST.get('age'),
                gender = request.POST.get('gender'),
                email = request.user.email,
                phone_number = request.POST.get('phone_number'),
                train = tt
            )
            tt.save()
            a.save()

            return render(request, './error.html', {'msg': "Booked ticket and paid Rs."+str(tt.price)+" sucessfully!"})
        
        context = {'form': form}
        return render(request, './person_form.html', context)
    else:
        return render(request, './error.html', {'msg': "User not authenticated"})


def bookform(request):
    t = trains.objects.all()
    sources = []
    destinations = []
    for i in t:
        sources.append(i.source)
        destinations.append(i.destination)
    sources = list(set(sources))
    destinations = list(set(destinations))

    if request.user.is_authenticated:
        return render(request, './booking.html', {'sources': sources, 'destinations':destinations})
    else:
        return render(request, './error.html', {'msg': "User not authenticated"})


def mybooking(request):
    if request.user.is_authenticated:
        p = person.objects.filter(email=request.user.email)
        return render(request, './mybooking.html', {'persons': p})
    else:
        return render(request, './error.html', {'msg': "User not authenticated"})
    

        
        

reservation/templates/addtrain.html
{% extends './base.html' %}
{% block content %}

<div class="container" style="display: flex;align-items: center;justify-content: center;margin-top: 100px;">
    <div class='jumbotron' style='width: 75%; '>
        
        <center><div style="margin-bottom: 40px;"><h1>Add Trains</h1></div></center>

        <form method='POST' action='/addtrain/'>
            {% csrf_token %}

            <div class="form-group row">
                <label class='form-label col-sm-2' for="name">Train Name</label>
                <div class='col-sm-10'>
                    <input type="text" class="form-control" id="train_name" placeholder='Enter the Name of the train' name="train_name">
                </div>
            </div>

            <div class="form-group row">
                <label class='form-label col-sm-2' for="name">Source</label>
                <div class='col-sm-10'>
                    <input type="text" class="form-control" id="source" placeholder='Enter the Source' name="source">
                </div>
            </div>

            <div class="form-group row">
                <label class='form-label col-sm-2' for="name">Destination</label>
                <div class='col-sm-10'>
                    <input type="text" class="form-control" id="destination" placeholder='Enter the Destination' name="destination">
                </div>
            </div>

            <div class="form-group row">
                <label class='form-label col-sm-2' for="name">Date</label>
                <div class='col-sm-10'>
                    <input type="date" class="form-control" id="date" placeholder='Enter Date' name="date">
                </div>
            </div>

            <div class="form-group row">
                <label class='form-label col-sm-2' for="name">Time</label>
                <div class='col-sm-10'>
                    <input type="time" class="form-control" id="time" placeholder='Enter the Time' name="time">
                </div>
            </div>

            <div class="form-group row">
                <label class='form-label col-sm-2' for="name">Seats Available</label>
                <div class='col-sm-10'>
                    <input type="text" class="form-control" id="seats_available" placeholder='Enter the No of Seats' name="seats_available">
                </div>
            </div>

            <div class="form-group row">
                <label class='form-label col-sm-2' for="name">Price</label>
                <div class='col-sm-10'>
                    <input type="text" class="form-control" id="price" placeholder='Enter the Price' name="price">
                </div>
            </div>

            <center><input type="submit" class="btn btn-success" value='Add'></center>

        </form>
    </div>
</div>
{% endblock %}

reservation/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <style>
        body {
          background-image: url('https://images.unsplash.com/photo-1518024291416-3244cd4a85b2?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1974&q=80');      
        }

    </style>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Railway website</title>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <ul class="navbar-nav">

            {% if request.user.is_superuser %}

            <span class="navbar-brand mb-0 h1">Admin</span>
            {% else %}
            <span class="navbar-brand mb-0 h1">{{request.user.username}}</span>

            {% endif %}
            <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000/">Home</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000/bookform/">Book ticket</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000/mybooking/">My Bookings</a>
            </li>

            {% if request.user.is_superuser %}
            <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000/trainform/">Add Trains</a>
            </li>
            {% endif %}

            {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000/logout/">Logout</a>
            </li>
            {% else %}

            <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000/loginform/">Login</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000/registerform/">Register</a>
            </li>

            {% endif %}
        </ul>
    </nav>

</head>
{% block content %}
{% endblock %}

</html>

reservation/templates/booking.html
{% extends './base.html' %}
{% block content %}

<div class="container" style="display: flex;align-items: center;justify-content: center;margin-top: 50px;">
    <div class='jumbotron' style='width: 100%; '>

        <center>
            <div style="margin-bottom: 40px;">
                <h1>Welcome {{request.user.username}} !</h1>
            </div>
        </center>

        <form method='POST' action='/book/'>
            {% csrf_token %}

            <div class="form-group row">
                <label class='form-label col-sm-2' for="source">Source</label>
                <div class='col-sm-10'>

                    <select class="form-control" id="source" name="source" required>
                        {%for t in sources%}
                        <option value={{t}}>{{t}}</option>
                        {% endfor %}
                    </select>

                </div>

            </div>

            <div class="form-group row">
                <label class='form-label col-sm-2' for="destination">Destination</label>
                <div class='col-sm-10'>
                  
                    <select class="form-control" id="destination" name="destination" required>
                        {%for t in destinations%}
                        <option value={{t}}>{{t}}</option>
                        {% endfor %}
                    </select>

                </div>
            </div>

            <div class="form-group row">
                <label class='form-label col-sm-2' for="date" required>Date</label>
                <div class='col-sm-10'>
                   <input type="date" id="date" name="date" />
                </div>
            </div>

            <center><input type="submit" class="btn btn-success" value='Search'></center>

        </form>
    </div>
</div>
{% endblock %}

reservation/templates/error.html
{% extends './base.html' %}

{% block content %}
<h5 style="margin:50px;">
    <center>
        {{msg}}
    </center>
</h5>
{% endblock content %}

reservation/templates/login.html
{% extends './base.html' %}
{% block content %}

<div class="container" style="display: flex;align-items: center;justify-content: center;margin-top: 150px;">
    <div class='jumbotron' style='width: 50%; '>
        
        <center><div style="margin-bottom: 40px;"><h1>Login</h1></div></center>

        <form method='POST' action='http://127.0.0.1:8000/login/'>
            {% csrf_token %}
            <div class="form-group row">
                <label class='form-label col-sm-2' for="name">Username</label>
                <div class='col-sm-10'>
                    <input type="text" class="form-control" id="name" placeholder='Enter the Username' name="name">
                </div>
            </div>

            <div class="form-group row">
                <label class='form-label col-sm-2' for="amount">Password</label>
                <div class='col-sm-10'>
                    <input type="password" class="form-control" placeholder='Enter the Password' id="password" name="password">
                </div>
            </div>

            <center><input type="submit" class="btn btn-success" value='Login'></center>

        </form>
    </div>
</div>
{% endblock %}

reservation/templates/mybooking.html
{% extends "./base.html" %}

{% block content %}

<div style="margin-top: 50px;">
    <center><h2> My Bookings </h2></center>

    <table class="table table-striped" style="width: 90%;margin-left:75px ;margin-top: 30px;">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Train Number</th>
                <th scope="col">Train Name</th>
                <th scope="col">Source</th>
                <th scope="col">Destination</th>
                <th scope="col">Name</th>
                <th scope="col">Age</th>
                <th scope="col">Gender</th>
                <th scope="col">Phone Number</th>
                <th scope="col">Date and time of booking</th>
            </tr>
        </thead>
        <tbody>
            {%for p in persons%}
            
            <tr class="table-light">
                <td>{{p.train.pk}}</td>
                <td>{{p.train.train_name}}</td>
                <td>{{p.train.source}}</td>
                <td>{{p.train.destination}}</td>
                <td>{{p.name}}</td>
                <td>{{p.age}}</td>
                <td>{{p.gender}}</td>
                <td>{{p.phone_number}}</td>
                <td>{{p.date_and_time_of_booking}}</td>
            </tr>
            </tbody>
            
            {% endfor %}
        </tbody>
    </table>
</div>



{% endblock %}

reservation/templates/person_form.html
{% extends './base.html' %}
{% block content %}
<div class="jumbotron container mt-4">
<div style="margin:50px;" class="personForm">
<form method="POST" action="" >
    <center><h1>Enter the passenger details</h1></center>
    <br>
    {% csrf_token %}
    {{form.as_p}}
    <br>
    <center>
        <input type="submit" value="Submit and Pay" class="btn btn-info">
    </center>
    
</form>
</div>
</div>
<script src="https://code.jquery.com/jquery-2.2.4.js" integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI=" crossorigin="anonymous"></script>
<script>
    $(document).ready(function()
    {
        $("#id_gender").addClass("form-control");
        $("#id_age").addClass("form-control");
        $("#id_name").addClass("form-control");
        $("#id_phone_number").addClass("form-control");
    });
</script>
  
{% endblock %}

reservation/templates/register.html
{% extends './base.html' %}
{% block content %}

<div class="container" style="display: flex;align-items: center;justify-content: center;margin-top: 150px;">
    <div class='jumbotron' style='width: 50%; '>
        
        <center><div style="margin-bottom: 40px;"><h1>Register</h1></div></center>

        <form method='POST' action='http://127.0.0.1:8000/register/'>
            {% csrf_token %}
            <div class="form-group row">
                <label class='form-label col-sm-2' for="name">Username</label>
                <div class='col-sm-10'>
                    <input type="text" class="form-control" id="name" placeholder='Enter the Username' name="name">
                </div>
            </div>

            <div class="form-group row">
                <label class='form-label col-sm-2' for="name">Email</label>
                <div class='col-sm-10'>
                    <input type="email" class="form-control" id="email" placeholder='Enter the Email' name="email">
                </div>
            </div>

            <div class="form-group row">
                <label class='form-label col-sm-2' for="amount">Password</label>
                <div class='col-sm-10'>
                    <input type="password" class="form-control" placeholder='Enter the Password' id="password" name="password">
                </div>
            </div>

            <center><input type="submit" class="btn btn-success" value='Register'></center>

        </form>
    </div>
</div>
{% endblock %}

reservation/templates/trainsavailable.html
{% extends "./base.html" %}

{% block content %}

<div style="margin-top: 50px;">
    <center><h2> Trains </h2></center>

    <table class="table table-striped" style="width: 90%;margin-left:75px ;margin-top: 30px;">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Train Number</th>
                <th scope="col">Train Name</th>
                <th scope="col">Source</th>
                <th scope="col">Destination</th>
                <th scope="col">Date</th>
                <th scope="col">Time</th>
                <th scope="col">Price</th>
                <th scope="col">Seats Available</th>
                <th scope="col">Booking</th>
            </tr>
        </thead>
        <tbody>
            {%for p in trains%}
            
            <tr class="table-light">
                <td>{{p.pk}}</a></td>
                <td>{{p.train_name}}</td>
                <td>{{p.source}}</td>
                <td>{{p.destination}}</td>
                <td>{{p.date}}</td>
                <td>{{p.time}}</td>
                <td>{{p.price}}</td>
                <td>{{p.seats_available}}</td>
                <td><a href="http://127.0.0.1:8000/booking/{{p.pk}}"><button class='btn btn-success'>Book Ticket</button></a></td>
            </tr>
            
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

reservation/templates/viewperson.html
{% extends "./base.html" %}
{% block content %}

<body>
    <div class='jumbotron'>
        <h3> Train Details </h3>
        <ul>
            <li>Train Number = {{train.pk}}</li>
            <li>Train Name = {{train.train_name}}</li>
            <li>Source = {{train.source}}</li>
            <li>Destination = {{train.destination}}</li>
            <li>Time = {{train.time}}</li>
            <li>Seats Available = {{train.seats_available}}</li>
            <li>Price for 1 ticket = {{train.price}}</li>
        </ul>
    </div>
    <div style="margin-top: 50px;">
        <center><h2 style="color: aliceblue; background-color: black; " class="container">People Reserved</h2></center>
     
        <table class="table table-striped  " style="width: 90%;margin-left:75px ;margin-top: 30px;">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Email</th>
                    <th scope="col">Name</th>
                    <th scope="col">Age</th>
                    <th scope="col">Gender</th>
                    <th scope="col">Date and time of booking</th>
                </tr>
            </thead>
            <tbody>
                {%for p in persons%}
                <tr class="table-light">
                    <td>{{p.email}}</td>
                    <td>{{p.name}}</td>
                    <td>{{p.age}}</td>
                    <td>{{p.gender}}</td>
                    <td>{{p.date_and_time_of_booking}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    
    </div>
</body>
{% endblock %}

reservation/templates/viewtrains.html
<!doctype html>
<html lang="en">

<head>
    <style>
        img
        {
            height: 600px;
        }
    </style>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>

    <title>Railway website</title>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <ul class="navbar-nav">

            {% if request.user.is_superuser %}

            <span class="navbar-brand mb-0 h1">Admin</span>
            {% else %}
            <span class="navbar-brand mb-0 h1">{{request.user.username}}</span>

            {% endif %}
            <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000/">Home</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000/bookform/">Book ticket</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000/mybooking/">My Bookings</a>
            </li>

            {% if request.user.is_superuser %}
            <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000/trainform/">Add Trains</a>
            </li>
            {% endif %}

            {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000/logout/">Logout</a>
            </li>
            {% else %}

            <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000/loginform/">Login</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000/registerform/">Register</a>
            </li>

            {% endif %}
        </ul>
    </nav>

</head>

<div class="container">
    <div id="carouselExampleIndicators" class="carousel slide">
        <div class="carousel-indicators">
          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="https://images.unsplash.com/photo-1527839321757-ad3a2f2be351?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item">
            <img src="https://static.theprint.in/wp-content/uploads/2019/07/Vande-Bharat.jpg?compress=true&quality=80&w=376&dpr=2.6" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item">
            <img src="https://images.unsplash.com/photo-1615652437548-dea5540d223f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80" class="d-block w-100" alt="...">
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
      </div>
    <div style="margin-top: 50px;">
        <center><h2> Trains </h2></center>
    
        <table class="table table-striped" style="width: 90%;margin-left:75px ;margin-top: 30px;">
            <thead class="table-dark">
                <tr>
                    <th scope="col">Train Number</th>
                    <th scope="col">Train Name</th>
                    <th scope="col">Source</th>
                    <th scope="col">Destination</th>
                    <th scope="col">Date</th>
                    <th scope="col">Time</th>
                    <th scope="col">Price</th>
                    <th scope="col">Seats Available</th>
                    <th scope="col">Booking</th>
                </tr>
            </thead>
            <tbody>
                {%for p in lis %}
                
                <tr>
                    {% if request.user.is_superuser %}
                        <td><a href="http://127.0.0.1:8000/{{p.pk}}">{{p.pk}}</a></td>
                    {% else %}
                        <td>{{p.pk}}</td>
                    {% endif %}
                    <td>{{p.train_name}}</td>
                    <td>{{p.source}}</td>
                    <td>{{p.destination}}</td>
                    <td>{{p.date}}</td>
                    <td>{{p.time}}</td>
                    <td>{{p.price}}</td>
                    <td>{{p.seats_available}}</td>
                    <td><a href="http://127.0.0.1:8000/booking/{{p.pk}}"><button class='btn btn-success'>Book Ticket</button></a></td>
                </tr>
                
                {% endfor %}
    
            </tbody>
        </table>
    </div>
    


</html>